### ISSUE TITLE
Is is possible to use SessionScope to throttle requests by IP address?

### ISSUE THREAD

**Issue by gkimpson** [bandwidth-throttle/token-bucket#3]
Is it possible to use SessionScope to limit requests by an unique identifier such as their IP address? 

Ideally something that would be able to 'kick' requests if an IP has made over a set allocation within a set time frame, e.g if the limit is 1000 requests per hour, once they make the 1001th request within that window rather than sleep it will just discard the request until they allowed to make requests again in the next window.

**Comment by malkusch** [comment]
You could do that, if you consider the IP-address as the throttled resource. I would even recommend using a global scope as forging new sessions is too easy:

```
$storage = new FileStorage(__DIR__ . "/$ipAddress.bucket");
$rate    = new Rate(1000, Rate::HOUR);
$bucket  = new TokenBucket(1000, $rate, $storage);
$bucket->bootstrap(1000);

if (!$bucket->consume(1, $seconds)) {
    http_response_code(429);
    header(sprintf("Retry-After: %d", floor($seconds)));
    exit();
}
```

You'll have to take care of cleaning up old buckets (i.e. storage files in this case).
