### ISSUE TITLE
Tokens left

### ISSUE THREAD

**Issue by ala747** [bandwidth-throttle/token-bucket#7]
Hi!

Is there any way to know/access to how many tokens are left until reach the time limit?

Thanks!

**Comment by malkusch** [comment]
No, I didn't implement that. But if you convince me that this is a useful feature I would add that. What's your exact use case?

**Comment by ala747** [comment]
Hi, Markus. Thank you very much for your quick answer.

Well, I don't know if my case would be a widely extended one.

I'm implementing your great library to throttle an API. I'm using a monthly based rate and, as it is a relatively long time, I would like to give the client a way to "ask" us how many requests he has left to avoid "surprises", giving him the opportunity to ask us to extend his limit before he hits it.

What do you think? Makes sense for you?

**Comment by malkusch** [comment]
It makes sense. You'll get it.

**Comment by ala747** [comment]
Thank you! Don't hesitate to ping me if I can help you
