### ISSUE TITLE
BlockingConsumer: timeout parameter?

### ISSUE THREAD

**Issue by lkraav** [bandwidth-throttle/token-bucket#9]
Hey. I'm not sure whether a complete deadlock during blocking consumption could somehow occur or not, but isn't it generally healthy to have a failsafe for a blocking operation - such as a configurable timeout setting?

**Comment by malkusch** [comment]
Have a look at the [mutex implementations](https://github.com/malkusch/lock/tree/master/classes/mutex) of the underlying locking library. Almost all of them have a default timeout of 3 seconds and there's a [ticket for missing timeouts](https://github.com/malkusch/lock/issues/6).

However that's a detail which I did not expose in this API. But I agree, users can write more sane software with an explicit timeout. I'll add that.
